repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x"]
        files: ^(snap/hooks/|snap/local/runtime/|snap/local/build/|snap/local/testing/|test_multipass\.sh)

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, "{extends: relaxed, rules: {line-length: disable}}"]
        files: ^(snap/snapcraft\.yaml)$

  - repo: local
    hooks:
      - id: no-repeating-separators
        name: Check CLI accessibility (No repeating delimiters)
        entry: '(={4,}|-{4,}|\*{4,}|_{4,})'
        language: pygrep
        files: \.(sh|py|bats|yaml|yml)$

