name: Test on openSUSE Tumbleweed

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: opensuse-tumbleweed
      lxd_image: images:opensuse/tumbleweed
