name: Test on Arch Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    secrets: inherit
    with:
      distro: archlinux
      lxd_image: images:archlinux
