name: Test on Ubuntu Daily

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-distro-build.yml

  test:
    needs: build
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu-daily
      lxd_image: ubuntu-daily:devel
      snap_artifact_name: built-snap
