name: Test on Debian

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: debian
      lxd_image: images:debian
