name: Test on Ubuntu Daily

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu-daily
      lxd_image: ubuntu-daily:devel
