name: Test on Ubuntu Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu-core
