name: Test on openSUSE Leap

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: opensuse-leap
      lxd_image: images:opensuse
