name: Test on openSUSE Tumbleweed

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-distro-build.yml

  test:
    needs: build
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: opensuse-tumbleweed
      lxd_image: images:opensuse/tumbleweed
      snap_artifact_name: built-snap
