name: Test on Debian Stable

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-distro-build.yml

  test:
    needs: build
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: debian-stable
      lxd_image: images:debian/stable
      snap_artifact_name: built-snap
