name: Test on Fedora

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-distro-build.yml

  test:
    needs: build
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: fedora
      lxd_image: images:fedora
      snap_artifact_name: built-snap
