name: Test on Ubuntu Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu-core
