name: Test on Arch Linux

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-distro-build.yml

  test:
    needs: build
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: archlinux
      lxd_image: images:archlinux
      snap_artifact_name: built-snap
