name: Test on AlmaLinux

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: almalinux
      lxd_image: images:almalinux
