name: Test on Debian 12

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    secrets: inherit
    with:
      distro: debian-12
      lxd_image: images:debian/12
