name: Test on Rocky Linux

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: rockylinux
      lxd_image: images:rockylinux
