name: Test on Arch Linux

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: archlinux
      lxd_image: images:archlinux
