name: Test on Ubuntu Daily

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu-daily
      lxd_image: ubuntu-daily:devel
