name: Test on Rocky Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    secrets: inherit
    with:
      distro: rockylinux
      lxd_image: images:rockylinux
