name: Test on Ubuntu

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-distro-test.yml
    with:
      distro: ubuntu
      lxd_image: ubuntu:lts
